version: "2"
services:
  server:
    container_name: server
    image: yunhan0/koa-vue-fullstack:server
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"